### ISSUE TITLE
cho最新的版本都能弄成HEXO的，牛。

### ISSUE THREAD

**Issue by eurusd** [7ye/maupassant-hexo#1]
能修改成typecho的吗，谢谢。

**Comment by 7ye** [comment]
额，^_^，我不会typecho.

**Comment by eurusd** [comment]
hexo 运行不了你的主题，为什么呢？ 谢谢

$ hexo s
INFO Start processing
INFO Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
Unhandled rejection TypeError: D:\hexo\themes\maupassant\layout\base.jade:59
57| block content
58| .pure-u-1-4: #sidebar

> 59| each item in theme.widgets
> 60| != partial('_widget/' + item + '.jade')
> 61|
> 62| include _partial/footer

Cannot read property 'length' of undefined
at eval (eval at (D:\hexo\node_modules\hexo-renderer-jade\node_modules\jade\lib\index.js:218:8), :830:31)
at eval (eval at (D:\hexo\node_modules\hexo-renderer-jade\node_modules\jade\lib\index.js:218:8), :855:4)
at eval (eval at (D:\hexo\node_modules\hexo-renderer-jade\node_modules\jade\lib\index.js:218:8), :1252:22)
at res (D:\hexo\node_modules\hexo-renderer-jade\node_modules\jade\lib\index.js:219:38)
at _compiled (D:\hexo\node_modules\hexo\lib\theme\view.js:127:30)
at View.render (D:\hexo\node_modules\hexo\lib\theme\view.js:29:15)
at D:\hexo\node_modules\hexo\lib\hexo\index.js:387:25
at tryCatcher (D:\hexo\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
at D:\hexo\node_modules\hexo\node_modules\bluebird\js\release\method.js:15:34
at RouteStream._read (D:\hexo\node_modules\hexo\lib\hexo\router.js:134:3)
at RouteStream.Readable.read (_stream_readable.js:336:10)
at resume_ (_stream_readable.js:733:12)
at nextTickCallbackWith2Args (node.js:442:9)
at process._tickCallback (node.js:356:17)

**Comment by 7ye** [comment]
唔，我对不起你，_config.yml文件里面配置有问题，我重新上传个，你再试试

**Comment by eurusd** [comment]
能帮忙把我现有主题的logo改成你这样的字体吗？还有就是一个侧边的竖线。
